format_version: 3
pipelines:  
  dropwizard-pipeline:
    lock_behavior: lockOnFailure
    group: CI_Project
    materials:
      repo:
        git: https://github.com/manu863018/MV_CI_Project.git
        branch: Acceptance_GoCD
    stages:
      - Build:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "capsule"
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: Build                                            
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:                       
                      - "test"   
                      - "jacocoTestReport"                                         
              artifacts:
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html       
                - build:
                    source: build/reports/jacoco/**/*
                    destination: jacoco                     
                - test:
                    source: build/test-results/test/*.xml
                    destination: xml                    
              tabs:
                unit_test: html/index.html                 
                code_coverage: jacoco/index.html
      - CodeQuality:
          jobs:
            Check:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:                      
                      - "sonarqube"
                      - "check"
              artifacts:
                - build:
                    source: build/reports/pmd/main.html
                    destination: pmd_html       
                - build:
                    source: build/reports/pmd/test.html
                    destination: pmd_html    
                - build:
                    source: build/reports/findbugs/main.html
                    destination: findbugs_html     
                - build:
                    source: build/reports/findbugs/test.html
                    destination: findbugs_html                                         
              tabs:
                pmd_main: pmd_html/main.html                 
                pmd_test: pmd_html/test.html      
                findbugs_main: findbugs_html/main.html                 
                findbugs_test: findbugs_html/test.html                      
      - Deploy:
          jobs:
            deploying:
              tasks:
                - fetch:                    
                    stage: Build
                    job: building
                    source: Build/              
                - exec:
                    command: ./gradlew
                    arguments:                                            
                      - "-b"   
                      - "deploy.gradle"
                      - "deploy"
                      - "-Pdev_server=10.28.109.121"
                      - "-Pjar_path=Build"                      
      - Acceptance:
          jobs:
            testing:
              tasks:
                - exec:
                    command: ./AT_Framework/gradlew
                    arguments:                                            
                      - "clean"
                      - "test"                       
                      - "-p"
                      - "AT_Framework/"      
              artifacts:
                - build:
                    source: AT_Framework/build/reports/cucumberhtml/cucumber-html-reports/*
                    destination: cucumberReport      
              tabs:
                cucumber: cucumberReport/overview-features.html                     

