format_version: 3
pipelines:  
  dropwizard-pipeline:
    lock_behavior: lockOnFailure
    group: CI_Project
    materials:
      repo:
        git: https://github.com/devops-at06/MV_CI_Project.git
        branch: master
    stages:
      - Build:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "assemble"
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: Build
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments: 
                      - "clean"
                      - "test"   
                      - "jacocoTestReport"                      
              artifacts:
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html       
                - build:
                    source: build/reports/jacoco/**/*
                    destination: jacoco
                - test:
                    source: build/test-results/test/*.xml
                    destination: xml                    
              tabs:
                unit_test: html/index.html                 
                code_coverage: jacoco/index.html 
      - CodeQuality:
          jobs:
            Check:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - sonarqube                                          
 
