format_version: 3
pipelines:  
  dropwizard-pipeline:
    lock_behavior: lockOnFailure
    group: CI_Project
    materials:
      repo:
        git: https://github.com/manu863018/MV_CI_Project.git
        branch: GoCD_deploy_stage
    stages:
      - Build:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "capsule"
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: Build                                            
 